package users;
/** This is the abstract class representing User
 * 
 */
public abstract class User {
	
	protected int id;
	protected String name;
	protected String username;
	protected String hashedPassword;
	/** 
	 * 	Constructs a User with a given name,username and password , the id is generated by a UserIdGenerator
	 * @param name represents the name of the User
	 * @param username represents the username of the User that allows him to login into the system
	 * @param hashedPassword represents the hashed password of the User 
	 */
	public User( String name,String username, String password) {
		UserIdGenerator idgen = UserIdGenerator.getInstance();
		this.id = idgen.getNextUserId();
		this.name = name;
		this.username = username;
		this.hashedPassword = PasswordHasher.hashPassword(password);
	}
	/**
	 * Gets the User's id
	 */
	
	public int getId() {
		return id;
	}
	
	/** 
	 * Gets the User's name
	 */
	
	public String getName() {
		return name;
	}
	
	/**
	 * Sets the User's name
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * Gets the User's username
	 */
	public String getUsername() {
		return username;
	}
	/**
	 * Sets the User's username
	 */
	public void setUsername(String username) {
		this.username = username;
	}
	/** 
	 * Gets the User's hashed password
	 */
	public String getHashedPassword() {
		return hashedPassword;
	}
	/**
	 * Sets the User's hashed password
	 */
	public void setHashedPassword(String password) {
		this.hashedPassword = password;
	}
	
}
